name: Scheduled Update

on:
  schedule:
    # Run every 6 hours to check for new content from RSS feeds
    - cron: '0 */6 * * *'
  workflow_dispatch:

# Allow only one concurrent execution
concurrency:
  group: "scheduled-update"
  cancel-in-progress: false

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      actions: write
      deployments: write
    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site with fresh content
        run: npm run build
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          QIITA_API_TOKEN: ${{ secrets.QIITA_API_TOKEN }}

      - name: Check for changes
        id: check-changes
        run: |
          # Check if there are any changes in the built site
          if git diff --quiet HEAD -- public; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to GitHub Pages
        if: steps.check-changes.outputs.changes == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Scheduled update from ${{ github.sha }}'

      - name: Notification
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          echo "Site updated and deployed successfully"
        
      - name: No update notification  
        if: steps.check-changes.outputs.changes == 'false'
        run: |
          echo "No content updates found, skipping deployment"
